### ISSUE TITLE
6. Z 字形变换 – 数据结构与算法精选100题

### ISSUE THREAD

**Issue by krahets** [jin407891080/CodingSolution#23]
https://krahets.com/

**Comment by krahets** [comment]
Test comment :)

**Comment by HelWireless** [comment]
你好啊，想知道那个配图的gif是怎么做的？一帧一帧做的嘛？

**Comment by krahets** [comment]
> 你好啊，想知道那个配图的gif是怎么做的？一帧一帧做的嘛？

是的，静态图片播放的哈哈

**Comment by HelWireless** [comment]
果然，想做好背后都得做很多工作呀------------------ 原始邮件 ------------------
发件人: "Krahets"<notifications@github.com>
发送时间: 2019年11月13日(星期三) 晚上6:45
收件人: "krahets/CodingSolution"<CodingSolution@noreply.github.com>;
抄送: "MR He"<2587225803@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [krahets/CodingSolution] 6. Z 字形变换 – 数据结构与算法精选100题 (#23)


 
你好啊，想知道那个配图的gif是怎么做的？一帧一帧做的嘛？
  
是的，静态图片播放的&#x54C8;&#x54C8;
 
&mdash;
