### ISSUE TITLE
About – 数据结构与算法精选100题

### ISSUE THREAD

**Issue by krahets** [jin407891080/CodingSolution#24]
https://krahets.com/about/

**Comment by krahets** [comment]
Test

**Comment by sybil63** [comment]
研究了两天你的blog，下次接着研究字体库。不会前端的后端真是太惨了。

给后来者：
* 这位大神的Blog用了Jekyll的Moon主题[https://github.com/TaylanTatli/Moon](https://github.com/TaylanTatli/Moon)。（要自定义修改先看Jekyll的ReadMe）
* 把comment换成了gitment（坑挺多，最好新建一个git的Repo放评论，每个页面的id要不同,gitment.js里的post地址是最大的坑）。
* css改得很好，估计是[https://github.com/krahets/teal-theme-diy](https://github.com/krahets/teal-theme-diy)这个项目。
